### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by lunaryorn** [lunaryorn/gnome-search-providers-vscode#1]
Tracking issue for features missing from https://github.com/Jomik/vscode-search-provider

- Support missing VSCode variants (see [original list](https://github.com/Jomik/vscode-search-provider/blob/master/extension.ts#L61))
- Search for files (I don't need this myself and will not implement it)
- Search prefix (don't need this either and won't do it)

**Comment by StephenCoady** [comment]
I would like to help out with a couple of things here. I don't need the 2nd two features you listed either but I would like to help extend the supported variants. 

I have zero experience with dbus interfacing and I'm not sure how to discover them. For example on my system when I run `qdbus` I don't see any mention of vscode. If you could point me to resources that would help me figure out how to do this I'd be happy to create a PR.

**Comment by lunaryorn** [comment]
Thank you, but I just don't have time to provide assistance.  I am sorry but you'll have to find out for yourself.  Checkout the DBus spec/documentation, the code in this repo, and past pull request for I think there was one already about adding a new VSCode variant.

Sorry, that's all I can offer.  Other than that you're on your own I'm afraid.
