### ISSUE TITLE
Support multi-root workspaces

### ISSUE THREAD

**Issue by vianney** [lunaryorn/gnome-search-providers-vscode#14]
Multi-root workspaces are saved as `.code-workspace` configuration files. They appear as follows in the `storage.json` file:

```json
{
  "openedPathsList": {
    "entries": [
      {
        "workspace": {
          "id": "0123456789abcdef0123456789abcdef",
          "configPath": "file:///path/to/myworkspace.code-workspace"
        }
      }
    ]
  }
}
```
(tested on VSCodium 1.62.3)

Currently, such entires are ignored. It would be nice if they could also appear in the search results.

**Comment by lunaryorn** [comment]
You'll need to open s merge request because I don't have any such workspace.

**Comment by lunaryorn** [comment]
I've made a new release with your patch :)
