### ISSUE TITLE
Fedora support

### ISSUE THREAD

**Issue by Merrit** [lunaryorn/gnome-search-providers-vscode#17]
> Visual Studio Code (AUR package)

Is there something preventing this from working on Fedora? I have installed according to the instructions, however I don't see any results in search nor does it show up in Search settings

**Comment by lunaryorn** [comment]
It's not as if there's a "this runs only on Arch" flag somewhere :wink:  but every VSCode distro package seems to have its own way of naming things, and so far this thing here supports only what I know and use.

You'd need to figure out the name of the desktop file of your VSCode installation on Fedora (presumably the official package from the website?) and then make a pull request like https://github.com/lunaryorn/gnome-search-providers-vscode/pull/6 to add it :slightly_smiling_face:

**Comment by Merrit** [comment]
Yep, I see the issue now. Thanks for getting back to me :grin: 

I will put together a pull request shortly. :+1:

**Comment by lunaryorn** [comment]
Closed by #18
