### ISSUE TITLE
Stopped working with Code Insiders - change to storage.json

### ISSUE THREAD

**Issue by harshadgavali** [lunaryorn/gnome-search-providers-vscode#22]
There's upcoming change which storage list of opened folders in sqlite database instead of storage.json .
Change is already on insider builds.

https://github.com/microsoft/vscode/issues/138072

**Comment by lunaryorn** [comment]
Thanks.  I'll remember it, and address it once it starts affecting me 🙂🙏

**Comment by lunaryorn** [comment]
@harshadgavali I've moved my repos to codeberg.org so you may want to subscribe to https://codeberg.org/flausch/gnome-search-providers-vscode/issues/22
