### ISSUE TITLE
stuck at "Searching..." on gnome 3.38.4

### ISSUE THREAD

**Issue by SantoJambit** [lunaryorn/gnome-search-providers-vscode#3]
I've tried following the instructions to install it, but once I do install it and type in a search, it gets stuck at "Searching...". When I uninstall it, I get "no results" as expected during a search.

Where can I find error logs that might help identify the issue?

**Comment by lunaryorn** [comment]
In `systemctl --user status de.swsnr.searchprovider.Jetbrains.service` and `journalctl -xe`.

**Comment by SantoJambit** [comment]
```console
Starting VSCode workspaces search provider for Gnome shell...
de.swsnr.searchprovider.VSCode.service: Failed to locate executable /usr/lib/gnome-search-providers-vscode/gnome-search-providers-vscode: No such file or directo>
de.swsnr.searchprovider.VSCode.service: Failed at step EXEC spawning /usr/lib/gnome-search-providers-vscode/gnome-search-providers-vscode: No such file or direct>
de.swsnr.searchprovider.VSCode.service: Main process exited, code=exited, status=203/EXEC
de.swsnr.searchprovider.VSCode.service: Failed with result 'exit-code'.
Failed to start VSCode workspaces search provider for Gnome shell.
```

It gets installed to /usr/local/lib, but it is expected at /usr/lib, maybe that is the issue?

**Comment by SantoJambit** [comment]
This file lists /usr/lib as location: https://github.com/lunaryorn/gnome-search-providers-vscode/blob/main/dbus-1/de.swsnr.searchprovider.VSCode.service

Should this be changed to /usr/local/lib?

**Comment by lunaryorn** [comment]
Oh, indeed.  I changed the standard prefix in `Makefile` in the aftermath, and forgot that it'd need to be changed in the service and DBus files as well :confused: 

Just changing it in the unit file won't do though; this would just break if you installed to `/usr`.  The Makefile would somehow need to replace the prefix in the service file upon installation, with some `sed` foo.  I'll perhaps fix this at some point but currently this is not that important to me.

If you'd like to submit a pull request to automatically update the Unit and the DBus service file during `make install` I'd be very happy, but if you're just after a quick fix you can also edit the unit file manually, i.e.

```console
# Replace /usr with /usr/local
$ sudoedit /usr/local/lib/systemd/user/de.swsnr.searchprovider.VSCode 
$ systemctl --user daemon-reload
$ systemctl --user restart de.swsnr.searchprovider.VSCode.service
```
