### ISSUE TITLE
Ordered results

### ISSUE THREAD

**Issue by SantoJambit** [lunaryorn/gnome-search-providers-vscode#7]
In the gnome-extension, sorting would appear as in the storage.json, i.e. recently used entries would appear on top. Here, due to the hash-map being used, order is random.
Any particular reason why you chose a hash-map? For smaller sizes, often the overhead of a map results in less performant queries compared to a list search. Not sure about rust though.

If you don't want to use a list, should we store the original position, so we can sort this at the end?

**Comment by lunaryorn** [comment]
The extension used a map as well. 

I'd like to keep the map interface because the code needs to look by ID, but I don't cling to an unordered hash map.

I guess you could use eg the indexmap crate to maintain insertion order.

I for my part don't care, I usually type specific search terms until there's just one or two matches left.

**Comment by SantoJambit** [comment]
I'm guessing, that with javascript hash maps, they are iterated in the order they get added. At least for objects it's that way I think.

About #2, I think it would be nice if that was configurable. Via json file maybe? I'm thinking. "orderMode": "most-recently-used" vs "best-match".

**Comment by lunaryorn** [comment]
> I'm guessing, that with javascript hash maps, they are iterated in the order they get added. At least for objects it's that way I think.

I don't know; the extension used a map not an indexed object, though.

> About #2, I think it would be nice if that was configurable. Via json file maybe? I'm thinking. "orderMode": "most-recently-used" vs "best-match".

Let us please discuss this in #2.

**Comment by lunaryorn** [comment]
@SantoJambit The change was simple enough so I fixed it right away.

**Comment by SantoJambit** [comment]
Thanks!
